config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
    has_many :bookmarks, dependent: :destroy
    has_many :movies, through: :bookmarks

    validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks

    validates :title, uniqueness: true, presence: true
    validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  private
  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a new movie to <%= @list.name %></h1>

<%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.association :movie, as: :select %>
    <%= f.input :comment %>
    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList962</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Watch Lists</h1>

<%= link_to "+", new_list_path %>

<% @lists.each do |list| %>
    <%= link_to list_path(list) do %>
        <div class="card">
            <%= list.name %>
        </div>
    <% end %>
<% end %>

app/views/lists/new.html.erb
<h1>Add a new List!</h1>
<%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<%= link_to "Add a movie", new_list_bookmark_path(@list) %>
<% @list.bookmarks.each do |bm| %>
    <div class="card">
        <h2><%= bm.movie.title %></h2>
        <p><%= bm.movie.overview %></p>
        <p><%= bm.comment %></p>
        <%= link_to '<i class="fa-solid fa-trash"></i>'.html_safe, bookmark_path(bm), data: {turbo_method: :delete} %>
    </div>
<% end %>